name: Deploy PWA to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      env:
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_TENANT_ID: ${{ secrets.REACT_APP_TENANT_ID }}
        REACT_APP_DATAVERSE_URL: ${{ secrets.REACT_APP_DATAVERSE_URL }}
        REACT_APP_BUILD_TIME: ${{ github.run_number }}
        REACT_APP_BUILD_HASH: ${{ github.sha }}
        REACT_APP_BUILD_BRANCH: ${{ github.ref_name }}
        REACT_APP_BUILD_NUMBER: ${{ github.run_number }}
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        cname: diskgolf-pwa.netlify.app
